#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.event
Version  : 4.3.0
Release  : 4
URL      : https://pypi.debian.net/zope.event/zope.event-4.3.0.tar.gz
Source0  : https://pypi.debian.net/zope.event/zope.event-4.3.0.tar.gz
Summary  : Very basic event publishing system
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.event-python
Requires: Sphinx
Requires: setuptools
Requires: zope.testrunner
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
``zope.event`` README
        =======================

%package python
Summary: python components for the zope.event package.
Group: Default

%description python
python components for the zope.event package.


%prep
%setup -q -n zope.event-4.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1501029792
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.6/site-packages python3 setup.py test
%install
export SOURCE_DATE_EPOCH=1501029792
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
